name: 'Delete and create tag'
description: 'Used to delete a tag and recreate it. Useful for internal environment releases. Not intended for production'
inputs:
  repository:
    description: 'Repository name with owner'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  tag-name:
    description: 'Tag name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: lyric-tech/common-ci/actions/docker/delete-tag@develop
      with:
        repository: ${{ inputs.repository }}
        tag-name: ${{ inputs.tag-name }}
        token: ${{ inputs.token }}
    - uses: lyric-tech/common-ci/actions/docker/create-tag@develop
      with:
        repository: ${{ inputs.repository }}
        tag-name: ${{ inputs.tag-name }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
