variables:
  ARTIFACT_S3_PATH: $ARTIFACT_S3_PATH
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IMAGE_REPO: $ORG_ID/note/$CI_PROJECT_NAME
  DOCKER_REGISTRY: $DOCKER_REGISTRY
  DOCKER_TAG: $CI_COMMIT_REF_NAME
  DOCKER_TLS_CERTDIR: ''
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

workflow:
  rules:
  - if: $CI_COMMIT_REF_NAME == "main"
    variables:
      DOCKER_TAG: latest
  - when: always

build_artifact:
  after_script:
  - mv .lyric/build/artifact.zip .
  allow_failure: false
  artifacts:
    expire_in: 1 week
    paths:
    - artifact.zip
  image: $DOCKER_REGISTRY/$DOCKER_IMAGE_REPO:$DOCKER_TAG
  script:
  - python3 -m chainbrain.utils.build_utils --version $CI_COMMIT_REF_NAME --image-url
    $DOCKER_IMAGE_REPO:$DOCKER_TAG
  stage: build_artifact

docker_publish:
  allow_failure: false
  before_script:
  - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  - aws ecr describe-repositories --repository-names $DOCKER_IMAGE_REPO || aws ecr
    create-repository --repository-name $DOCKER_IMAGE_REPO --image-scanning-configuration
    scanOnPush=true --encryption-configuration '{"encryptionType":"KMS"}'
  image:
    entrypoint:
    - ''
    name: $DOCKER_REGISTRY/gitlab-ci-image:latest
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
  - when: on_success
  script:
  - curl https://gitlab.com/sairam_lyric/note-common/-/raw/main/python/Dockerfile.base > Dockerfile.base 
  - DOCKER_BUILDKIT=1 docker build 
    --cache-from $DOCKER_IMAGE_REPO:$DOCKER_TAG 
    --build-arg private_repo_username=chainbrain-token 
    --build-arg private_repo_token=$CHAINBRAIN_TOKEN 
    --build-arg docker_registry=$DOCKER_REGISTRY 
    -t $DOCKER_REGISTRY/$DOCKER_IMAGE_REPO:$DOCKER_TAG .
  - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_REPO:$DOCKER_TAG
  stage: docker_publish

publish_artifact:
  image:
    name: $DOCKER_REGISTRY/gitlab-ci-image:latest
  script:
  - aws configure set region $AWS_DEFAULT_REGION
  - aws s3 cp artifact.zip $ARTIFACT_S3_PATH/$CI_PROJECT_NAME/$CI_PROJECT_NAME_$DOCKER_TAG.zip
  stage: publish_artifact
services:
- docker:stable-dind
stages:
- docker_publish
- build_artifact
- publish_artifact

