name: Publish Package to Centralised Artiactory

on:
  workflow_call:
    inputs: 
      REPO_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string
    secrets:
      REPO_GITHUB_TOKEN:
        required: true
      AWS_ROLE_ARN:
        required: true

permissions:
  contents: write
  pages: write
  id-token: write
  repository-projects: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: lyric-tech/${{ inputs.REPO_NAME }}
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          ref: ${{ inputs.BRANCH_NAME }}

      - name: Check Version in poetry file
        run: |
          fileVersion=`cat pyproject.toml | grep version`         
          if [ $fileVersion -ne ${{ input.BRANCH_NAME }} ]; then
            echo "Version mismatch in pyproject.toml"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-duration-seconds: 900

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install Twine
        run: |
          pip install wheel twine
          pip install poetry

      - name: Setting Version
        run: |
          poetry version ${{ inputs.PACKAGE_VERSION }}

      - name: Build Package
        run: |
          poetry build

      - name: Publish Package
        run: |
          aws codeartifact login --tool twine --domain lyric --repository lyric-artifact
          aws codeartifact delete-package-versions --domain lyric --domain-owner 111122223333 \
            --repository lyric-artifact --format pypi \
            --package ${{ inputs.REPO_NAME }} --versions ${{ inputs.BRANCH_NAME }} | true
          echo "Publishing Package"
          twine upload --repository codeartifact dist/* --verbose