name: Build and publish docker

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      ECR_REGISTRY:
        required: true
      ECR_REPOSITORY:
        required: true
        
jobs:
  docker_publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
        # Build a docker container and push it to ECR 
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }} || true
        docker build --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }} -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }} .

        echo "Pushing Image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }}
        echo "::group::Image Tag"
        echo "${{ inputs.image_tag }}"
        echo "::endgroup::"
