name: API Test

on:
  workflow_call:
    inputs: 
      REPO_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
    secrets:
      REPO_GITHUB_TOKEN:
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api_test:
    name: API Test for developmnent2
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.REPO_NAME }}
        token: ${{ secrets.REPO_GITHUB_TOKEN }}
        ref: ${{ inputs.BRANCH_NAME }}

    - name: Install dependencies
      run: |
        npm install

    - name: Run API Test
      continue-on-error: true
      run: |
        npm run test-appservice

    - name: Update index file
      run: |
        mv ./reports/html-report/report.html ./reports/html-report/index.html
        mv ./reports/html-report .
    
    - name: Setup Pages
      uses: actions/configure-pages@v2
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
          path: './reports/html-report'
          
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: './reports/html-report'
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
