name: Microservice Docker Build and publish

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      BASE_DIRECTORY:
        default: '.'
        type: string
    secrets:
      LYRIC_GITHUB_USERNAME:
        required: false
      LYRIC_GITHUB_TOKEN:
        required: false
      CHAINBRAIN_TOKEN:
        required: false
      AWS_DEFAULT_REGION:
        required: true
      AWS_ROLE_ARN:
        required: true
      GCP_WORKLOAD_IDENTITY:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_PROJECT_ID:
        required: true
             
permissions:
  id-token: write
  contents: write 
  repository-projects: write
  
jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Docker meta for ECR
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}
          us-docker.pkg.dev/$GCP_PROJECT_ID/lyric/$ECR_REPOSITORY
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{version}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        config: .github/buildkitd.toml
   
    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        IMAGE_TAG: "${{ inputs.IMAGE_TAG }}"
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
        BASE_DIRECTORY: ${{ inputs.BASE_DIRECTORY }}
        CHAINBRAIN_TOKEN: ${{ secrets.CHAINBRAIN_TOKEN }}
        LYRIC_GITHUB_USERNAME: ${{ secrets.LYRIC_GITHUB_USERNAME }}
        LYRIC_GITHUB_TOKEN: ${{ secrets.LYRIC_GITHUB_TOKEN }}      
      with:
        context: ${{ inputs.BASE_DIRECTORY }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
            private_repo_username=chainbrain-token
            private_repo_token=${{ secrets.CHAINBRAIN_TOKEN }}
            github_username=${{ secrets.LYRIC_GITHUB_USERNAME }}
            github_token=${{ secrets.LYRIC_GITHUB_TOKEN }}
            docker_registry=${{ steps.login-ecr.outputs.registry }}