name: Microservice API Test Sequence

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      REPO_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
    secrets:
      API_URL:
        required: true
      REPO_GITHUB_TOKEN:
        required: true
        
permissions:
  id-token: write
  contents: write 
  repository-projects: write

jobs:
  api_test:
    name: API Test for ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.REPO_NAME }}
        path: ${{ inputs.BRANCH_NAME }}
        token: ${{ secrets.REPO_GITHUB_TOKEN }}

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        npm install --frozen-lockfile --force

    - name: Run API Test
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        npm test spec/ url=${{ secrets.API_URL }}
