name: Python CI Template

on:
  workflow_call:

permissions:
  id-token: write
  contents: read 
  
jobs:
  kube_deploy:
    name: Python CI Run and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        echo "Installing Dependency"
        #pip install pipenv==2022.8.5
        #pipenv lock && pipenv requirements > requirements.txt
        #pip install -r requirements.txt
    - name: Run Unit Test
      run: |
        echo "Running Unit Test"