name: NPM Pull Request Common File

on:
  workflow_call:

permissions:
  id-token: write
  contents: write 
  repository-projects: write
  
jobs:
  build:
    name: NPM Install and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps --frozen-lockfile --force
      
    - name: Build
      run: npm run build --if-present
      
    - name: Run Unit Test
      run: npm test
