name: API Test

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      API_URL:
        required: true
      REPO_NAME:
        required: true

jobs:
  api_test:
    name: API Test for ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPO_NAME }}

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install --frozen-lockfile --force

    - name: Run API Test
      run: npm test spec/ url=${{ secrets.API_URL }}
