name: API Test

on:
  workflow_call:
    inputs: 
      REPO_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
    secrets:
      REPO_GITHUB_TOKEN:
        required: true

jobs:
  api_test:
    name: API Test for developmnent2
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.REPO_NAME }}
        path: ${{ inputs.BRANCH_NAME }}
        token: ${{ secrets.REPO_GITHUB_TOKEN }}
        ref: ${{ inputs.BRANCH_NAME }}

    - name: Install dependencies
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        npm install

    - name: Run API Test
      continue-on-error: true
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        sleep 10m
        npm run test-appservice
        mv ./html-report/report.html ./html-report/index.html

    - name: Update index file
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        mv ./html-report/report.html ./html-report/index.html
        
    - name: Publish Test Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.LYRIC_TOKEN }}
        publish_dir: ./html-report
