name: API Test

on:
  workflow_call:
    inputs: 
      REPO_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
    secrets:
      REPO_GITHUB_TOKEN:
        required: true

jobs:
  api_test:
    name: API Test for developmnent2
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.REPO_NAME }}
        path: ${{ inputs.BRANCH_NAME }}
        token: ${{ secrets.REPO_GITHUB_TOKEN }}
        ref: ${{ inputs.BRANCH_NAME }}

#    - name: Use Node.js 16.x
#      uses: actions/setup-node@v3
#      with:
#        node-version: 16.x
#        cache: 'npm'
#        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        npm install

    - name: Run API Test
      run: |
        cd ${{ inputs.BRANCH_NAME }}
        ls -ltr *
        cd api
        ls -ltr */**
        npm run test-appservice
