name: API Test

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      REPO_NAME:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
    secrets:
      API_URL:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  api_test:
    name: API Test for ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.REPO_NAME }}
        path: ${{ inputs.BRANCH_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install --frozen-lockfile --force

    - name: Run API Test
      run: npm test spec/ url=${{ secrets.API_URL }}
