name: Note Docker Build and publish docker

on:
  workflow_call:
    inputs:
      NOTE_TAG:
        required: true
        type: string
      NOTE_REPOSITORY_NAME:
        required: true
        type: string
      NOTE_CI_TEMPLATE_VERSION:
        required: true
        type: string
      BASE_DIRECTORY:
        default: '.'
        type: string           
    secrets:
      LYRIC_GITHUB_USERNAME:
        required: false
        description: 'Github username for private repo access'
      LYRIC_GITHUB_TOKEN:
        required: false
        description: 'Github token for private repo access'
      GITLAB_USERNAME:
        required: false
        description: 'Gitlab username for private repo access'
      GITLAB_TOKEN:
        required: false
        description: 'Gitlab token for private repo access'
      ORG_ID:
        required: true
        description: 'Organization ID for Docker Registry'
      AWS_DEFAULT_REGION:
        required: true
        description: 'AWS region for ECR'
      AWS_ROLE_ARN:
        required: true
        description: 'AWS role ARN for ECR'
      ECR_REGISTRY:
        required: true
        description: 'ECR registry for ECR'
      GCR_REGISTRY:
        required: true
        description: 'GCR registry for GCR'
      GCP_WORKLOAD_IDENTITY:
        required: true
        description: 'GCP workload identity for GCR'
      GCP_SERVICE_ACCOUNT:
        required: true
        description: 'GCP service account for GCR'
      GCP_PROJECT_ID:
        required: true
        description: 'GCP project ID for GCR'
      ACR_ENDPOINT:
        required: true
        description: 'ACR endpoint for ACR'
      ACR_USERNAME:
        required: true
        description: 'ACR username for ACR'
      ACR_PASSWORD:
        required: true
        description: 'ACR password for ACR'        
        

permissions:
  id-token: write
  contents: write 
  repository-projects: write

jobs:
  docker_publish:
    name: Build and Publish Notes Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # Set note env variables
    - name: Set note env variables
      env:
        ORG_ID: ${{ secrets.ORG_ID }}
        NOTE_REPOSITORY_NAME: ${{ inputs.NOTE_REPOSITORY_NAME }}
      run: |
        echo "NOTE_NAME=$(echo $NOTE_REPOSITORY_NAME | sed 's/note-//')" >> $GITHUB_ENV
        echo "NOTE_IMAGE_REPO=$ORG_ID/note/$(echo $NOTE_REPOSITORY_NAME | sed 's/note-//')" >> $GITHUB_ENV

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'
  
    # Create ECR repository
    - uses: int128/create-ecr-repository-action@v1
      with:
        repository: ${{ env.NOTE_IMAGE_REPO }}
        lifecycle-policy: .github/config/lifecycle-policy.json
          
    # Login to Google Cloud
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # Login to Google Cloud Registry
    - name: Login to GCR
      uses: docker/login-action@v2
      env:
        gcr_password: ${{ steps.auth.outputs.access_token}}
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ env.gcr_password }}

    # Login to Azure Container Registry
    - name: Log into ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Get Docker meta
    - name: Docker meta for ECR
      id: meta
      uses: docker/metadata-action@v3    
      with:
        images: |
          ${{ secrets.ECR_REGISTRY }}/${{ env.NOTE_IMAGE_REPO }}
          ${{ secrets.GCR_REGISTRY }}/lyric/${{ env.NOTE_IMAGE_REPO }}
          ${{ secrets.ACR_ENDPOINT }}/${{ env.NOTE_IMAGE_REPO }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    # Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Download note base dockerfile
    - name: Download note base dockerfile
      env:
        NOTE_CI_TEMPLATE_VERSION: ${{ inputs.NOTE_CI_TEMPLATE_VERSION }}
      run: |
        curl https://raw.githubusercontent.com/lyric-tech/common-ci/${NOTE_CI_TEMPLATE_VERSION}/note/Dockerfile.spark.base > Dockerfile.base
        curl https://raw.githubusercontent.com/lyric-tech/common-ci/${NOTE_CI_TEMPLATE_VERSION}/note/Dockerfile.spark.base > Dockerfile.spark.base
        curl https://raw.githubusercontent.com/lyric-tech/common-ci/${NOTE_CI_TEMPLATE_VERSION}/note/Dockerfile.pandas2.base > Dockerfile.pandas2.base
        curl https://raw.githubusercontent.com/lyric-tech/common-ci/${NOTE_CI_TEMPLATE_VERSION}/note/Dockerfile.pandas1.base > Dockerfile.pandas1.base
        curl https://raw.githubusercontent.com/lyric-tech/common-ci/${NOTE_CI_TEMPLATE_VERSION}/note/Dockerfile.polars.base > Dockerfile.polars.base

    # Build and push
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.BASE_DIRECTORY }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          private_repo_username=${{ secrets.GITLAB_USERNAME }}
          private_repo_token=${{ secrets.GITLAB_TOKEN }}
          gitlab_username=${{ secrets.GITLAB_USERNAME }}
          gitlab_token=${{ secrets.GITLAB_TOKEN }}
          github_username=${{ secrets.LYRIC_GITHUB_USERNAME }}
          github_token=${{ secrets.LYRIC_GITHUB_TOKEN }}
          docker_registry=${{ secrets.ECR_REGISTRY }}
          chainbrain_version=${{ secrets.CHAINBRAIN_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
