name: CI for Python Note Developers

on:
  workflow_call:
    inputs:
      NOTE_TAG:
        required: true
        type: string
      NOTE_REPOSITORY_NAME:
        required: true
        type: string
      NOTE_CI_TEMPLATE_VERSION:
        required: true
        type: string
    secrets:
      LYRIC_GITHUB_USERNAME:
        required: true
      LYRIC_GITHUB_TOKEN:
        required: true
      CHAINBRAIN_TOKEN:
        required: true
      ORG_ID:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_ECR_ROLE_ARN:
        required: true
      AWS_S3_ROLE_ARN:
        required: true
      ARTIFACT_S3_PATH:
        required: true
      GCP_WORKLOAD_IDENTITY:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_PROJECT_ID:
        required: true


permissions:
  id-token: write
  contents: write 
  repository-projects: write
  
jobs:
  promote_artifact:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') == true && (contains("${{ inputs.NOTE_REPOSITORY_NAME }}", "datasource"}) || contains("${{ inputs.NOTE_REPOSITORY_NAME }}", "transformer")) 
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Set note env variables
        run: |
          echo "Building Artifact ${{ inputs.NOTE_REPOSITORY_NAME }}"
