name: Publish artifact

on:
  workflow_call:
    inputs:
      NOTE_TAG:
        required: true
        type: string
        description: 'Tag of the note to promote'
      NOTE_REPOSITORY_NAME:
        required: true
        type: string
        description: 'Name of the note repository to promote'
    secrets:
      AWS_DEFAULT_REGION:
        required: true
        description: 'AWS region'
      AWS_ROLE_ARN:
        required: true
        description: 'AWS role to assume'
      GCP_WORKLOAD_IDENTITY:
        required: true
        description: 'GCP workload identity'
      GCP_SERVICE_ACCOUNT:
        required: true
        description: 'GCP service account'
      GCP_PROJECT_ID:
        required: true
        description: 'GCP project id'
      AZURE_CONNECTIONSTRING:
        required: true
        description: 'Azure connection string'

permissions:
  id-token: write
  contents: write 
  repository-projects: write

jobs:
  publish_artifact:
    name: Publish Artifact to S3
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-duration-seconds: 900

      - name: Set note env variables
        env:
          NOTE_REPOSITORY_NAME: ${{ inputs.NOTE_REPOSITORY_NAME }}
        run: |
          echo "NOTE_NAME=$(echo $NOTE_REPOSITORY_NAME | sed 's/note-//')" >> $GITHUB_ENV

      - name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
            
      - name: Upload artifact to S3/GCS File Storages
        env:
          ARTIFACT_S3_PATH: ${{ secrets.ARTIFACT_S3_PATH }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NOTE_TAG: ${{ inputs.NOTE_TAG }}
        run: |
          aws configure set region $AWS_DEFAULT_REGION
          aws s3 cp ./artifact.zip s3://lyric-store-lyric/note_artifacts/lyric/${NOTE_NAME}/${NOTE_NAME}_${NOTE_TAG}.zip
          gsutil cp ./artifact.zip gs://lyric-store-lyric/note_artifacts/lyric/${NOTE_NAME}/${NOTE_NAME}_${NOTE_TAG}.zip

      - name: Copy Artifcat to Azure Blob
        uses: azure/CLI@v1
        env:
          NOTE_TAG: ${{ inputs.NOTE_TAG }}
        with:
          azcliversion: latest
          inlineScript: |     
            az storage blob upload --connection-string '${{ secrets.AZURE_CONNECTIONSTRING }}' --container-name lyric-store-lyric --name note_artifacts/lyric/${NOTE_NAME}/${NOTE_NAME}_${NOTE_TAG}.zip --type block --file ./artifact.zip 
