name: Publish artifact

on:
  workflow_call:
    inputs:
      NOTE_FROM_TAG:
        required: true
        type: string
      NOTE_TO_TAG:
        required: true
        type: string
      NOTE_REPOSITORY_NAME:
        required: true
        type: string
    secrets:
      ARTIFACT_S3_PATH:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_S3_ROLE_ARN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:  
  setup_env_list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          echo "::set-output name=matrix::${{ vars.CUSTOMER_ENVS }}"

  promote_to_customer:
    name: Publish Artifact to Customer S3
    needs: setup_env_list
    strategy:
      matrix:
        customer: ${{fromJson(needs.setup.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_S3_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-duration-seconds: 900

      - name: Set note env variables
        env:
          NOTE_REPOSITORY_NAME: ${{ inputs.NOTE_REPOSITORY_NAME }}
        run: |
          echo "NOTE_NAME=$(echo $NOTE_REPOSITORY_NAME | sed 's/note-//')" >> $GITHUB_ENV

      - name: Promote artifact to Customer and Demo Environment
        env:
          ARTIFACT_S3_PATH: ${{ secrets.ARTIFACT_S3_PATH }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NOTE_TAG: ${{ inputs.NOTE_TAG }}
        run: |
          aws configure set region $AWS_DEFAULT_REGION
          aws s3 cp ${ARTIFACT_S3_PATH}/${NOTE_NAME}/${NOTE_NAME}_${NOTE_FROM_TAG}.zip .
          aws s3 cp ${NOTE_NAME}_${NOTE_FROM_TAG}.zip ${ARTIFACT_S3_PATH}/${{ matrix.customer }}/${NOTE_NAME}/${NOTE_NAME}_${NOTE_TO_TAG}.zip