name: CI for Python Note Developers

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
    secrets:
      AWS_DEFAULT_REGION:
        required: true
      AWS_ECR_ROLE_ARN:
        required: true
      AWS_S3_ROLE_ARN:
        required: true
      ORG_NAME:
        required: true
      ARTIFACT_S3_PATH:
        required: true
      GCP_WORKLOAD_IDENTITY:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_PROJECT_ID:
        required: true        
      ECR_REGISTRY:
        required: true
      GCR_REGISTRY:
        required: true
      ACR_ENDPOINT:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

permissions:
  id-token: write
  contents: write 
  repository-projects: write
     
jobs:
  build_artifact:
      name: Build Artifact
      runs-on: ubuntu-latest
      container:
        image: python:3.10-alpine
      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Build artifact
          run: |
            apt-get install -y git
            mkdir .lyric/build
            jq --arg version $HOME --arg date "$(date +%FT%XZ)" \
              -s '.[0] * { dataSchema: .[1] } * { parametersSchema: .[2] } * { workflowTemplate: .[3] } * { buildMetadata: { version: $version, build_time: $date } }' \
              .lyric/note_config.json .lyric/data_schema.json .lyric/parameters_schema.json .lyric/workflow_template.json > .lyric/build/note-metadata.json
            zip -urj artifact.zip .lyric/build/note-metadata.json

        - name: Store artifact
          uses: actions/upload-artifact@v3
          with:
            name: artifact
            path: artifact.zip
            retention-days: 7

  docker_publish:
    needs: build_artifact
    uses: ./.github/workflows/note-docker-publish.yml
    with:
      image_tag: ${{ inputs.image_tag }}
      ECR_REPOSITORY: ${{ inputs.REPOSITORY_NAME }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ECR_ROLE_ARN }}
      LYRIC_GITHUB_TOKEN: ${{ secrets.LYRIC_GITHUB_TOKEN }}
      LYRIC_GITHUB_USERNAME: ${{ secrets.LYRIC_GITHUB_USERNAME }}
      CHAINBRAIN_TOKEN: ${{ secrets.CHAINBRAIN_TOKEN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      GCR_REGISTRY: ${{ secrets.GCR_REGISTRY }}
      GCP_WORKLOAD_IDENTITY: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      ACR_ENDPOINT: ${{ secrets.ACR_ENDPOINT }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}  

  publish_artifact:
    needs: build_artifact
    uses: ./.github/workflows/note-artifact-publish.yml
    with:
      build_version: ${{ inputs.image_tag }}
      ARTIFACT_NAME: ${{ inputs.REPOSITORY_NAME }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_S3_ROLE_ARN }}
      ORG_NAME: ${{ secrets.ORG_NAME }}
      LYRIC_GITHUB_TOKEN: ${{ secrets.LYRIC_GITHUB_TOKEN }}
      LYRIC_GITHUB_USERNAME: ${{ secrets.LYRIC_GITHUB_USERNAME }}
      CHAINBRAIN_TOKEN: ${{ secrets.CHAINBRAIN_TOKEN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      GCR_REGISTRY: ${{ secrets.GCR_REGISTRY }}
      GCP_WORKLOAD_IDENTITY: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      ACR_ENDPOINT: ${{ secrets.ACR_ENDPOINT }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}        