name: CI for Python Notes

on:
  workflow_call:
    inputs:
      NOTE_TAG:
        required: true
        type: string
        description: 'Tag for the note'
      NOTE_REPOSITORY_NAME:
        required: true
        type: string
        description: 'Name of the note repository'
      NOTE_CI_TEMPLATE_VERSION:
        required: true
        type: string
        default: 'latest'        
        description: 'Version of the CI template to use'
    secrets:
      LYRIC_GITHUB_USERNAME:
        required: false
        description: 'Github username for private repo access'
      LYRIC_GITHUB_TOKEN:
        required: false
        description: 'Github token for private repo access'
      GITLAB_USERNAME:
        required: false
        description: 'Gitlab username for private repo access'
      GITLAB_TOKEN:
        required: false
        description: 'Gitlab token for private repo access'
      ORG_ID:
        required: true
        description: 'Organization ID for Docker Registry'
      AWS_DEFAULT_REGION:
        required: true
        description: 'AWS region for ECR'
      AWS_ECR_ROLE_ARN:
        required: true
        description: 'AWS role ARN for ECR'
      AWS_S3_ROLE_ARN:
        required: true
        description: 'AWS role ARN for S3'        
      ECR_REGISTRY:
        required: true
        description: 'ECR registry for ECR'
      GCR_REGISTRY:
        required: true
        description: 'GCR registry for GCR'
      GCP_WORKLOAD_IDENTITY:
        required: true
        description: 'GCP workload identity for GCR'
      GCP_SERVICE_ACCOUNT:
        required: true
        description: 'GCP service account for GCR'
      GCP_PROJECT_ID:
        required: true
        description: 'GCP project ID for GCR'
      ACR_ENDPOINT:
        required: true
        description: 'ACR endpoint for ACR'
      ACR_USERNAME:
        required: true
        description: 'ACR username for ACR'
      ACR_PASSWORD:
        required: true
        description: 'ACR password for ACR'       
      AZURE_CONNECTIONSTRING:
        required: true
        description: 'Azure connection string for Azure Blob Storage'
          

permissions:
  id-token: write
  contents: write 
  repository-projects: write
  
jobs:
  build_artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set note env variables
        env:
          ORG_ID: ${{ secrets.ORG_ID }}
          NOTE_REPOSITORY_NAME: ${{ inputs.NOTE_REPOSITORY_NAME }}
        run: |
          echo "NOTE_NAME=$(echo $NOTE_REPOSITORY_NAME | sed 's/note-//')" >> $GITHUB_ENV
          echo "NOTE_IMAGE_REPO=$ORG_ID/note/$(echo $NOTE_REPOSITORY_NAME | sed 's/note-//')" >> $GITHUB_ENV

      - name: Build artifact
        env:
          NOTE_TAG: "${{ inputs.NOTE_TAG == 'main' && 'latest' || inputs.NOTE_TAG }}"
          LYRIC_GITHUB_USERNAME: ${{ secrets.LYRIC_GITHUB_USERNAME }}
          LYRIC_GITHUB_TOKEN: ${{ secrets.LYRIC_GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        run: |
          echo "note_name & tag & repo: $NOTE_NAME, $NOTE_TAG, $NOTE_IMAGE_REPO"
          touch artifact.zip

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.zip
          retention-days: 1

  publish_artifact:
    needs: build_artifact
    uses: ./.github/workflows/note_artifact_publish.yml
    with:
      NOTE_TAG: "${{ inputs.NOTE_TAG == 'main' && 'latest' || inputs.NOTE_TAG }}"
      NOTE_REPOSITORY_NAME: ${{ inputs.NOTE_REPOSITORY_NAME }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_S3_ROLE_ARN }}
      GCP_WORKLOAD_IDENTITY: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      AZURE_CONNECTIONSTRING: ${{ secrets.AZURE_CONNECTIONSTRING }}
      
  promote_artifact:
    needs: publish_artifact
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') == true && (contains(github.event.repository.name, 'datasource') == true || contains(github.event.repository.name, 'transformer') == true || contains(github.event.repository.name, 'nc-transformer' == true))
    uses: ./.github/workflows/note_artifact_promote.yml
    with:
      NOTE_TAG: "${{ inputs.NOTE_TAG == 'main' && 'latest' || inputs.NOTE_TAG }}"
      NOTE_REPOSITORY_NAME: ${{ inputs.NOTE_REPOSITORY_NAME }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_S3_ROLE_ARN }}
      GCP_WORKLOAD_IDENTITY: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      AZURE_CONNECTIONSTRING: ${{ secrets.AZURE_CONNECTIONSTRING }}