name: Microservice Docker Build and publish for notes

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
      BASE_DIRECTORY:
        default: '.'
        type: string
    secrets:
      LYRIC_GITHUB_USERNAME:
        required: true
      LYRIC_GITHUB_TOKEN:
        required: true
      GITLAB_USERNAME:
        required: false
      GITLAB_TOKEN:
        required: false
      AWS_ROLE_ARN:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      GCP_WORKLOAD_IDENTITY:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_PROJECT_ID:
        required: true
      ECR_REGISTRY:
        required: true
      GCR_REGISTRY:
        required: true
      ACR_ENDPOINT:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
                     
permissions:
  id-token: write
  contents: write 
  repository-projects: write
  
jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Login to GCR
      uses: docker/login-action@v2
      env:
        gcr_password: ${{ steps.auth.outputs.access_token}}
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ env.gcr_password }}

    - name: Log into ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Docker meta for ECR
      id: meta
      uses: docker/metadata-action@v3    
      with:
        images: |
          ${{ secrets.ECR_REGISTRY }}/${{ inputs.REPOSITORY_NAME }}
          ${{ secrets.GCR_REGISTRY }}/${{ inputs.REPOSITORY_NAME }}
          ${{ secrets.ACR_ENDPOINT }}/${{ inputs.REPOSITORY_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build, tag, and push image to Amazon ECR
      run: |
        aws ecr describe-repositories --repository-names $REPOSITORY_NAME || aws ecr create-repository \
          --repository-name $REPOSITORY_NAME --image-scanning-configuration scanOnPush=true \
          --encryption-configuration '{"encryptionType":"KMS"}' \
          --tags Key=sprinto,Value=prod Key=env,Value=prod 

    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        BASE_DIRECTORY: ${{ inputs.BASE_DIRECTORY }}
        CHAINBRAIN_TOKEN: ${{ secrets.CHAINBRAIN_TOKEN }}
        LYRIC_GITHUB_USERNAME: ${{ secrets.LYRIC_GITHUB_USERNAME }}
        LYRIC_GITHUB_TOKEN: ${{ secrets.LYRIC_GITHUB_TOKEN }}
      with:
        context: ${{ inputs.BASE_DIRECTORY }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
            private_repo_username=chainbrain-token
            private_repo_token=${{ secrets.CHAINBRAIN_TOKEN }}
            github_username=${{ secrets.LYRIC_GITHUB_USERNAME }}
            github_token=${{ secrets.LYRIC_GITHUB_TOKEN }}
            docker_registry=${{ secrets.ECR_REGISTRY }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
        cache-from: type=gha
        cache-to: type=gha,mode=max
