name: Update Notes Chainbrain Package

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      package-version:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      token:
        required: true
     
permissions:
  id-token: write
  contents: read 
  repository-projects: write
  
jobs:
  update_package:
    name: Update Notes with Chainbrain Package version ${{ inputs.package-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        token: ${{ secrets.token }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install poetry
        
    - name: Remove and Update Package
      run: |
        export GH_TOKEN=${{ secrets.token }}
        poetry remove chainbrain
        poetry add git+https://gitlab.com/chainbrain/platform/chainbrain.git#${{ inputs.package-version }}
      shell: bash

    - uses: lyric-tech/common-ci/actions/git/commit-push@develop
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        token: ${{ secrets.token }}
        message: "Updated to Chainbrain Package Version ${{ inputs.package-version }}"
